version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: churn_postgres
    restart: always
    environment:
      POSTGRES_USER: churn_user
      POSTGRES_PASSWORD: churn_password
      POSTGRES_DB: churn_project
    ports:
      - "5432:5432"
    volumes:
      - churn_postgres_data:/var/lib/postgresql/data

volumes:
  churn_postgres_data: